package tictactoe;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Araya
 */
public class VistaTicTacToe extends javax.swing.JFrame implements MouseListener {

    private TicTacToe ticTacToe;
    private JLabel matrizGrafica[][];

    public VistaTicTacToe() {
        this.ticTacToe = new TicTacToe();
        this.matrizGrafica = new JLabel[ticTacToe.getAreaJuego().length][ticTacToe.getAreaJuego().length];
        initComponents();
        this.setLocationRelativeTo(null);
        agregar();
        hiloIndicador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoJuego = new javax.swing.JPanel();
        panelIndicador = new javax.swing.JPanel();
        jlabelIndicador = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondoJuego.setBackground(new java.awt.Color(0, 0, 0));
        panelFondoJuego.setLayout(new java.awt.GridLayout(ticTacToe.getAreaJuego().length, ticTacToe.getAreaJuego().length, 5, 5));

        panelIndicador.setBackground(new java.awt.Color(153, 153, 153));

        jlabelIndicador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlabelIndicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIndicadorLayout = new javax.swing.GroupLayout(panelIndicador);
        panelIndicador.setLayout(panelIndicadorLayout);
        panelIndicadorLayout.setHorizontalGroup(
            panelIndicadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndicadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlabelIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        panelIndicadorLayout.setVerticalGroup(
            panelIndicadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIndicadorLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelIndicadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIndicador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFondoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        ticTacToe.vaciarAreaJuego();
        actualizar();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    public void agregar() {
        for (int i = 0; i < ticTacToe.getAreaJuego().length; i++) {
            for (int j = 0; j < ticTacToe.getAreaJuego().length; j++) {
                JLabel jl = new javax.swing.JLabel();
                jl.setBackground(new java.awt.Color(255, 255, 255));
                jl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jl.setForeground(new java.awt.Color(0, 0, 0));
                jl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jl.setOpaque(true);

                if (ticTacToe.getAreaJuego()[i][j] == 1) {
                    jl.setText("X");
                } else if (ticTacToe.getAreaJuego()[i][j] == 2) {
                    jl.setText("O");
                }

                matrizGrafica[i][j] = jl;
                matrizGrafica[i][j].addMouseListener(this);
                panelFondoJuego.add(matrizGrafica[i][j]);
            }
        }
    }

    public void actualizar() {
        panelFondoJuego.removeAll();
        agregar();
        revalidate();
    }

    public void hiloIndicador() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    jlabelIndicador.setText("Turno: " + ticTacToe.jugadorInvertido());
                }
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jlabelIndicador;
    private javax.swing.JPanel panelFondoJuego;
    private javax.swing.JPanel panelIndicador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        int contador = 0;

        for (int i = 0; i < ticTacToe.getAreaJuego().length; i++) {
            for (int j = 0; j < ticTacToe.getAreaJuego().length; j++) {

                if (e.getSource() == panelFondoJuego.getComponent(contador++)) {

                    if (ticTacToe.getAreaJuego()[i][j] == 0) {
                        ticTacToe.turno();
                        ticTacToe.getAreaJuego()[i][j] = ticTacToe.getTurno();
                        actualizar();
                        if (ticTacToe.gane(i, j)) {
                            JOptionPane.showMessageDialog(null, "Gano " + matrizGrafica[i][j].getText());
                            ticTacToe.detenerAreaJuego();
                        } else if (ticTacToe.empate()) {
                            JOptionPane.showMessageDialog(null, "Empate");
                        }
                    }

                }
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
